services:
  postgres:
    image: postgres:17
    container_name: athis-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: arquitetura
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  minio:
    # CORRIGIDO: O caminho correto do repositório comercial AIStor
    image: quay.io/minio/aistor/minio:latest
    container_name: athis-minio
    command: server /data --console-address ":9001" --license /config/minio.license
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: athis_minio
      MINIO_ROOT_PASSWORD: athis_minio_dev_secret
      # Ativa a validação da licença gratuita que você baixou
      MINIO_LICENSE: /config/minio.license
    volumes:
      - minio_data:/data
      # Garante que o arquivo baixado seja enviado ao container
      - ./minio.license/minio.license:/config/minio.license:ro

  minio-init:
    image: quay.io/minio/aistor/minio:latest
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: athis_minio
      MINIO_ROOT_PASSWORD: athis_minio_dev_secret
    entrypoint:
      - /bin/sh
      - -c
      - |
        until mc alias set local http://minio:9000 "$$MINIO_ROOT_USER" "$$MINIO_ROOT_PASSWORD"; do
          sleep 2
        done
        mc mb --ignore-existing local/bucket-local;
        mc anonymous set none local/bucket-local;


  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: athis-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/arquitetura?schema=public"
      PORT: "3000"
      SECRET_STR: "asg7-hnkenf-53jje7-63hdkk-72ggdjjd"
      LOGIN_EXPIRES: "1000000"
      MINIO_ENDPOINT: "minio"
      MINIO_PORT: "9000"
      MINIO_ACCESS_KEY: "athis_minio"
      MINIO_SECRET_KEY: "athis_minio_dev_secret"
      MINIO_BUCKET: "athis-images"
      MINIO_USE_SSL: "false"
    depends_on:
      - postgres
      - minio
    volumes:
      - ./Backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: athis-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./Frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
  minio_data:
