/**
 * Catálogo Central de Perguntas - Formulário Araçatiba 2026
 *
 * `codigo` é o identificador estável.
 * Todas as questões do CSV fonte da verdade estão definidas como ativas (`ativa: true`).
 * Questões legadas descontinuadas mantêm `ativa: false`.
 */

const facilitiesQuestions = [
  // SECTION: Identificação e Localização
  {
    formulario: "Facilities",
    codigo: "id_facilities",
    texto: "ID",
    tipo: "texto",
    ordem: 1,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Identificação"
  },
  {
    formulario: "Facilities",
    codigo: "num_levantamento",
    texto: "Numeração do levantamento:",
    tipo: "number",
    ordem: 2,
    obrigatoria: true,
    ativa: true,
    opcoes: [],
    categoria: "Identificação"
  },
  {
    formulario: "Facilities",
    codigo: "nome_morador",
    texto: "Nome do Morador:",
    tipo: "texto",
    ordem: 3,
    obrigatoria: true,
    ativa: true,
    opcoes: [],
    categoria: "Identificação"
  },
  {
    formulario: "Facilities",
    codigo: "idade",
    texto: "Idade:",
    tipo: "number",
    ordem: 4,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Identificação"
  },
  {
    formulario: "Facilities",
    codigo: "levantamento_enquadramento",
    texto: "Esse levantamento se enquadra:",
    tipo: "texto",
    ordem: 5,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Identificação"
  },
  {
    formulario: "Facilities",
    codigo: "cpf_rg",
    texto: "CPF ou RG (CPF é mais relevante!):",
    tipo: "number",
    ordem: 6,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Identificação"
  },
  {
    formulario: "Facilities",
    codigo: "localizacao",
    texto: "Localização:",
    tipo: "texto",
    ordem: 7,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Identificação"
  },
  {
    formulario: "Facilities",
    codigo: "endereco",
    texto: "Endereço:",
    tipo: "texto",
    ordem: 8,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Identificação"
  },
  {
    formulario: "Facilities",
    codigo: "bairro",
    texto: "Bairro:",
    tipo: "resposta_unica",
    ordem: 9,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    allowOther: true,
    categoria: "Identificação"
  },
  {
    formulario: "Facilities",
    codigo: "idade_residentes",
    texto: "Idade dos residentes (ex: 12, 13, 25):",
    tipo: "texto",
    ordem: 10,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Identificação"
  },
  {
    formulario: "Facilities",
    codigo: "telefone_contato",
    texto: "Telefone de contato (com DDD):",
    tipo: "texto",
    ordem: 11,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Identificação"
  },
  {
    formulario: "Facilities",
    codigo: "dono_telefone",
    texto: "Dono do Telefone:",
    tipo: "resposta_unica",
    ordem: 12,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Identificação"
  },

  // SECTION: Renda e Composição Familiar
  {
    formulario: "Facilities",
    codigo: "renda_mensal_total",
    texto: "Qual a Renda mensal familiar total?",
    tipo: "texto",
    ordem: 13,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Renda e Composição Familiar"
  },
  {
    formulario: "Facilities",
    codigo: "chefe_familia",
    texto: "Qual o modelo de chefia da família?",
    tipo: "resposta_unica",
    ordem: 14,
    obrigatoria: false,
    ativa: true,
    opcoes: [
      "Casa chefiada por uma mulher (mãe ou avó)",
      "Casa chefiada pelo homem (pai / avô)",
      "Chefia compartilhada entre mãe e pai",
      "Chefia compartilhada entre mãe e avó",
      "Chefia compartilhada entre irmãs\\irmãos",
      "Não há hierarquia\\chefia explícita"
    ],
    allowOther: true,
    categoria: "Renda e Composição Familiar"
  },
  {
    formulario: "Facilities",
    codigo: "criancas_1_a_5",
    texto: "Quantidade de crianças na 1º infância(1 a 5 anos)",
    tipo: "number",
    ordem: 15,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Renda e Composição Familiar"
  },
  {
    formulario: "Facilities",
    codigo: "criancas_6_a_9",
    texto: "Quantidade de crianças (6 a 9 anos)",
    tipo: "number",
    ordem: 16,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Renda e Composição Familiar"
  },
  {
    formulario: "Facilities",
    codigo: "pre_adolescentes_10_a_14",
    texto: "Quantidade de pré-adolescentes (10 a 14 anos)",
    tipo: "number",
    ordem: 17,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Renda e Composição Familiar"
  },
  {
    formulario: "Facilities",
    codigo: "adolescentes_15_a_19",
    texto: "Quantidade de Adolescentes (15 a 19 anos)",
    tipo: "number",
    ordem: 18,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Renda e Composição Familiar"
  },
  {
    formulario: "Facilities",
    codigo: "num_moradores",
    texto: "Quantidade de moradores no lote",
    tipo: "number",
    ordem: 19,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Renda e Composição Familiar"
  },
  {
    formulario: "Facilities",
    codigo: "casas_no_lote",
    texto: "Quantidade de casas no lote",
    tipo: "number",
    ordem: 20,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Renda e Composição Familiar"
  },
  {
    formulario: "Facilities",
    codigo: "familias_no_lote",
    texto: "Quantidade de famíias no lote",
    tipo: "number",
    ordem: 21,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Renda e Composição Familiar"
  },
  {
    formulario: "Facilities",
    codigo: "parentesco_casa",
    texto: "Relação de parentesco na casa",
    tipo: "resposta_unica",
    ordem: 22,
    obrigatoria: false,
    ativa: true,
    opcoes: ["Pessoa responsável", "Cônjuge", "Filho(a)", "Outro parente", "Empregado(a) doméstico(a)"],
    allowOther: true,
    categoria: "Renda e Composição Familiar"
  },
  {
    formulario: "Facilities",
    codigo: "parentesco_lote",
    texto: "Relação de parentesco no lote",
    tipo: "resposta_unica",
    ordem: 23,
    obrigatoria: false,
    ativa: true,
    opcoes: ["Pessoa responsável", "Cônjuge", "Filho(a)", "Outro parente", "Empregado(a) doméstico(a)"],
    allowOther: true,
    categoria: "Renda e Composição Familiar"
  },
  {
    formulario: "Facilities",
    codigo: "ocupacao_responsavel_1",
    texto: "Ocupação do responsável 1",
    tipo: "resposta_multipla",
    ordem: 24,
    obrigatoria: false,
    ativa: true,
    opcoes: ["Profissional liberal", "Assalariado", "Funcionário Público", "Dona de casa", "Estudante", "Estudante com bolsa", "Aposentado(idade)", "Aposentado (invalidez)", "Programa social", "MEI", "Informal", "-"],
    allowOther: true,
    categoria: "Renda e Composição Familiar"
  },
  {
    formulario: "Facilities",
    codigo: "ocupacao_responsavel_2",
    texto: "Ocupação do responsável 2",
    tipo: "resposta_multipla",
    ordem: 25,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Renda e Composição Familiar"
  },
  {
    formulario: "Facilities",
    codigo: "ocupacao_respondente_nao_responsavel",
    texto: "Ocupação do respontente não responsável(retirada)",
    tipo: "texto",
    ordem: 26,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Renda e Composição Familiar"
  },
  {
    formulario: "Facilities",
    codigo: "escolaridade",
    texto: "Escolaridade",
    tipo: "resposta_unica",
    ordem: 27,
    obrigatoria: false,
    ativa: true,
    opcoes: ["Não sabe ler", "Fund. incompleto", "Fund. Completo", "Médio incompleto", "Médio completo", "Sup. incompleto", "Sup completo", "Pós-graduação", "Não respondeu"],
    categoria: "Renda e Composição Familiar"
  },
  {
    formulario: "Facilities",
    codigo: "onde_estuda",
    texto: "Se for estudante, onde estuda?",
    tipo: "resposta_unica",
    ordem: 28,
    obrigatoria: false,
    ativa: true,
    opcoes: ["Na comunidade", "Outro bairro de Viana", "Outro município de RMGV"],
    categoria: "Renda e Composição Familiar"
  },
  {
    formulario: "Facilities",
    codigo: "empregabilidade_responsavel_1",
    texto: "Empregabilidade do responsável 1",
    tipo: "resposta_multipla",
    ordem: 29,
    obrigatoria: false,
    ativa: true,
    opcoes: ["Em casa", "Na comunidade", "Viana", "Vitória", "Vila Velha", "Cariacica", "Serra"],
    allowOther: true,
    categoria: "Renda e Composição Familiar"
  },
  {
    formulario: "Facilities",
    codigo: "empregabilidade_responsavel_2",
    texto: "Empregabilidade do responsável 2",
    tipo: "resposta_multipla",
    ordem: 30,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Renda e Composição Familiar"
  },
  {
    formulario: "Facilities",
    codigo: "auto_declaracao",
    texto: "A família se autodeclara:",
    tipo: "resposta_unica",
    ordem: 31,
    obrigatoria: false,
    ativa: true,
    opcoes: ["Nda", "branco", "Pardo", "Negro", "multirracial"],
    allowOther: true,
    categoria: "Renda e Composição Familiar"
  },
  {
    formulario: "Facilities",
    codigo: "considera_quilombola",
    texto: "A família se considera quilombola?",
    tipo: "resposta_unica",
    ordem: 32,
    obrigatoria: false,
    ativa: true,
    opcoes: ["Sim", "Não", "Optou não responder"],
    categoria: "Renda e Composição Familiar"
  },
  {
    formulario: "Facilities",
    codigo: "obs_quilombola",
    texto: "Observações sobre a pergunta anterior (A família se considera qulombola?)",
    tipo: "texto",
    ordem: 33,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Renda e Composição Familiar"
  },

  // SECTION: Saberes e Artesanato
  {
    formulario: "Facilities",
    codigo: "pratica_artesanato",
    texto: "Pratica de artesanato",
    tipo: "resposta_multipla",
    ordem: 34,
    obrigatoria: false,
    ativa: true,
    opcoes: ["Corte e costura", "Tecido(patchwork, fuxico etc.)", "Crochê\\tricô", "Pintura", "Saboaria", "Madeira", "Instrumentos afro", "Tranças", "Barro\\cerâmica", "Artesanato afro"],
    allowOther: true,
    categoria: "Saberes e Artesanato"
  },
  {
    formulario: "Facilities",
    codigo: "saberes_adquiridos",
    texto: "Saberes adquiridos",
    tipo: "resposta_multipla",
    ordem: 35,
    obrigatoria: false,
    ativa: true,
    opcoes: ["Cultivo de alimentos", "Práticas medicinais", "Pratos típicos", "Artesanato", "Música com instrumentos afro", "Conhecimentos históricos e oralidade"],
    allowOther: true,
    categoria: "Saberes e Artesanato"
  },

  // SECTION: Assistência Social e Saúde
  {
    formulario: "Facilities",
    codigo: "cadastrada_bolsa_familia",
    texto: "A família está cadastrada no Bolsa Família?",
    tipo: "resposta_unica",
    ordem: 36,
    obrigatoria: false,
    ativa: true,
    opcoes: ["Sim", "Não"],
    categoria: "Assistência Social e Saúde"
  },
  {
    formulario: "Facilities",
    codigo: "numero_nis",
    texto: "Caso a família esteja cadastrada no Bolsa Família, qual o número do NIS?",
    tipo: "texto",
    ordem: 37,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Assistência Social e Saúde"
  },
  {
    formulario: "Facilities",
    codigo: "comorbidades_membro_1",
    texto: "Comorbidades na família (membro 1)",
    tipo: "resposta_multipla",
    ordem: 38,
    obrigatoria: false,
    ativa: true,
    opcoes: ["Cardiovascular", "Respiratória", "Neurológica", "Diabetes", "Imunossupressão", "Não possui"],
    allowOther: true,
    categoria: "Assistência Social e Saúde"
  },
  {
    formulario: "Facilities",
    codigo: "comorbidades_membro_2",
    texto: "Comorbidades na família (membro 2)",
    tipo: "resposta_multipla",
    ordem: 39,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Assistência Social e Saúde"
  },
  {
    formulario: "Facilities",
    codigo: "comorbidades_membro_3",
    texto: "Comorbidades na família (membro 3)",
    tipo: "resposta_multipla",
    ordem: 40,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Assistência Social e Saúde"
  },
  {
    formulario: "Facilities",
    codigo: "comorbidades_membro_4",
    texto: "Comorbidades na família (membro 4)",
    tipo: "resposta_multipla",
    ordem: 41,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Assistência Social e Saúde"
  },
  {
    formulario: "Facilities",
    codigo: "obs_comorbidades",
    texto: "Observações sobre comorbidades",
    tipo: "texto",
    ordem: 42,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Assistência Social e Saúde"
  },
  {
    formulario: "Facilities",
    codigo: "deficiencia_membro_1",
    texto: "Pessoas com deficiência na família (membro 1)",
    tipo: "resposta_multipla",
    ordem: 43,
    obrigatoria: false,
    ativa: true,
    opcoes: ["Física", "Auditiva", "Visual", "Intelectual", "Psicossocial", "Não possui"],
    allowOther: true,
    categoria: "Assistência Social e Saúde"
  },
  {
    formulario: "Facilities",
    codigo: "deficiencia_membro_2",
    texto: "Pessoas com deficiência na família (membro 2)",
    tipo: "resposta_multipla",
    ordem: 44,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Assistência Social e Saúde"
  },
  {
    formulario: "Facilities",
    codigo: "deficiencia_membro_3",
    texto: "Pessoas com deficiência na família (membro 3)",
    tipo: "resposta_multipla",
    ordem: 45,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Assistência Social e Saúde"
  },
  {
    formulario: "Facilities",
    codigo: "deficiencia_membro_4",
    texto: "Pessoas com deficiência na família (membro 4)",
    tipo: "resposta_multipla",
    ordem: 46,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Assistência Social e Saúde"
  },
  {
    formulario: "Facilities",
    codigo: "obs_deficiencias",
    texto: "Observações sobre deficiências",
    tipo: "texto",
    ordem: 47,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Assistência Social e Saúde"
  },
  {
    formulario: "Facilities",
    codigo: "medicamento_uso_continuo",
    texto: "Medicamento de uso contínuo",
    tipo: "resposta_unica",
    ordem: 48,
    obrigatoria: false,
    ativa: true,
    opcoes: ["Sim", "Não", "Pega na farmácia popular do SUS"],
    categoria: "Assistência Social e Saúde"
  },
  {
    formulario: "Facilities",
    codigo: "finalidade_medicamento",
    texto: "Finalidade do medicamento",
    tipo: "texto",
    ordem: 49,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Assistência Social e Saúde"
  },
  {
    formulario: "Facilities",
    codigo: "doenca_respiratoria_membro_1",
    texto: "Pessoas com deficiência respiratória crônica (membro 1)",
    tipo: "resposta_multipla",
    ordem: 50,
    obrigatoria: false,
    ativa: true,
    opcoes: ["Asma", "Bronquite", "Rinite", "Sinusite", "Fibrose cística", "DPOC", "Câncer", "Tuberculose"],
    allowOther: true,
    categoria: "Assistência Social e Saúde"
  },
  {
    formulario: "Facilities",
    codigo: "doenca_respiratoria_membro_2",
    texto: "Pessoas com deficiência respiratória crônica (membro 2)",
    tipo: "resposta_multipla",
    ordem: 51,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Assistência Social e Saúde"
  },
  {
    formulario: "Facilities",
    codigo: "doenca_respiratoria_membro_3",
    texto: "Pessoas com deficiência respiratória crônica (membro 3)",
    tipo: "resposta_multipla",
    ordem: 52,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Assistência Social e Saúde"
  },
  {
    formulario: "Facilities",
    codigo: "obs_doencas_respiratorias",
    texto: "Observações sobre doenças respiratórias",
    tipo: "texto",
    ordem: 53,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Assistência Social e Saúde"
  },

  // SECTION: Imóvel e Moradia
  {
    formulario: "Facilities",
    codigo: "forma_aquisicao_imovel",
    texto: "Qual a forma de aquisição do imóvel?",
    tipo: "resposta_unica",
    ordem: 54,
    obrigatoria: false,
    ativa: true,
    opcoes: ["Herança", "Compra com recibo", "Posse", "Doação particular", "Refúgio", "Usucapião", "Doação pública", "Assentado", "Não sabe"],
    allowOther: true,
    categoria: "Imóvel e Moradia"
  },
  {
    formulario: "Facilities",
    codigo: "condicao_imovel",
    texto: "Condição do imóvel",
    tipo: "resposta_unica",
    ordem: 55,
    obrigatoria: false,
    ativa: true,
    opcoes: ["Emprestado \\ Cedido", "Alugado", "Próprio(comprado)", "Próprio(construído)"],
    categoria: "Imóvel e Moradia"
  },
  {
    formulario: "Facilities",
    codigo: "ano_construcao_casa",
    texto: "Sabem dizer em que ano a casa foi construída?",
    tipo: "number",
    ordem: 56,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Imóvel e Moradia"
  },
  {
    formulario: "Facilities",
    codigo: "obs_idade_construcao",
    texto: "Caso não saiba, escreva observações sobre a idade aproximada da construção",
    tipo: "texto",
    ordem: 57,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Imóvel e Moradia"
  },
  {
    formulario: "Facilities",
    codigo: "tempo_residencia_imovel",
    texto: "Há quanto tempo residem neste imóvel?",
    tipo: "number",
    ordem: 58,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Imóvel e Moradia"
  },
  {
    formulario: "Facilities",
    codigo: "obs_tempo_residencia_imovel",
    texto: "Caso não saiba, escreva observações sobre há quanto tempo residem no imóvel",
    tipo: "texto",
    ordem: 59,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Imóvel e Moradia"
  },
  {
    formulario: "Facilities",
    codigo: "quem_executou_casa",
    texto: "Quem executou a casa?",
    tipo: "resposta_multipla",
    ordem: 60,
    obrigatoria: false,
    ativa: true,
    opcoes: ["Pessoa da família", "Ajuda de vizinhos", "Profissional especializado", "Não sabe informar"],
    allowOther: true,
    categoria: "Imóvel e Moradia"
  },
  {
    formulario: "Facilities",
    codigo: "geracoes_na_casa",
    texto: "Quantas gerações moram na casa",
    tipo: "number",
    ordem: 61,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Imóvel e Moradia"
  },
  {
    formulario: "Facilities",
    codigo: "geracoes_no_lote",
    texto: "Quantas gerações moram no lote",
    tipo: "number",
    ordem: 62,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Imóvel e Moradia"
  },
  {
    formulario: "Facilities",
    codigo: "origem_cidade_bairro",
    texto: "Origem - cidade e bairro de origem",
    tipo: "resposta_multipla",
    ordem: 63,
    obrigatoria: false,
    ativa: true,
    opcoes: ["Sempre morei em araçatiba", "Morei em outros bairros de Viana", "Morei em outros municípios da RMGV", "Morei em outro município do ES", "Morei em outro estado"],
    allowOther: true,
    categoria: "Imóvel e Moradia"
  },
  {
    formulario: "Facilities",
    codigo: "outros_bairros_cidade_detalhes",
    texto: "Em caso de moradia em outro bairro cidade,  informe aqui",
    tipo: "resposta_multipla",
    ordem: 64,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    allowOther: true,
    categoria: "Imóvel e Moradia"
  },
  {
    formulario: "Facilities",
    codigo: "anos_residencia_aracatiba",
    texto: "Há quantos anos a família reside em Araçatiba",
    tipo: "number",
    ordem: 65,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Imóvel e Moradia"
  },
  {
    formulario: "Facilities",
    codigo: "obs_tempo_residencia_aracatiba",
    texto: "Caso não saiba, escreva observações sobre há quanto tempo residem em Araçatiba",
    tipo: "texto",
    ordem: 66,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Imóvel e Moradia"
  },
  {
    formulario: "Facilities",
    codigo: "possui_outro_imovel",
    texto: "A família possui algum outro imóvel ou terreno?",
    tipo: "resposta_multipla",
    ordem: 67,
    obrigatoria: false,
    ativa: true,
    opcoes: ["Não possui outro imóvel", "Possui outro imóvel na comunidade", "Possui outro imóvel em Viana", "Possui imóvel em outro município"],
    categoria: "Imóvel e Moradia"
  },
  {
    formulario: "Facilities",
    codigo: "valor_aluguel",
    texto: "Se a família está morando de aluguel, qual o valor?",
    tipo: "texto",
    ordem: 68,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Imóvel e Moradia"
  },
  {
    formulario: "Facilities",
    codigo: "imovel_teve_reforma",
    texto: "O imóvel já recebeu algum tipo de reforma ou ampliação",
    tipo: "resposta_unica",
    ordem: 69,
    obrigatoria: false,
    ativa: true,
    opcoes: ["Sim", "Não"],
    categoria: "Imóvel e Moradia"
  },
  {
    formulario: "Facilities",
    codigo: "tipo_reforma_executada",
    texto: "Que tipo de reforma foi executada",
    tipo: "texto",
    ordem: 70,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Imóvel e Moradia"
  },
  {
    formulario: "Facilities",
    codigo: "quem_executou_reforma",
    texto: "Quem executou a reforma",
    tipo: "resposta_multipla",
    ordem: 71,
    obrigatoria: false,
    ativa: true,
    opcoes: ["Os moradores", "Vizinhos da comunidade", "Contratou profissional especializado", "Não reformei"],
    allowOther: true,
    categoria: "Imóvel e Moradia"
  },
  {
    formulario: "Facilities",
    codigo: "quem_custeou_reforma",
    texto: "Quem custeou a reforma",
    tipo: "resposta_unica",
    ordem: 72,
    obrigatoria: false,
    ativa: true,
    opcoes: ["A prefeitura", "Outro recurso público", "Recurso próprio", "Não reformei"],
    allowOther: true,
    categoria: "Imóvel e Moradia"
  },

  // SECTION: Comunidade e Cotidiano
  {
    formulario: "Facilities",
    codigo: "boa_vivencia_vizinhos",
    texto: "Convivência com os vizinhos",
    tipo: "resposta_unica",
    ordem: 73,
    obrigatoria: false,
    ativa: true,
    opcoes: ["Boa relação", "Relação ruim", "Indiferente", "Não deseja ou não sabe informar"],
    allowOther: true,
    categoria: "Comunidade e Cotidiano"
  },
  {
    formulario: "Facilities",
    codigo: "formas_uso_quintal",
    texto: "Formas de uso do quintal",
    tipo: "resposta_multipla",
    ordem: 74,
    obrigatoria: false,
    ativa: true,
    opcoes: ["Reuniões\\Lazer", "Produção vegetal", "Ervas medicinais", "Produção animal", "Plantas ornamentais", "Garagem", "Guarda de utensílios", "Rituais religiosos", "Processamento de alimentos"],
    allowOther: true,
    categoria: "Comunidade e Cotidiano"
  },
  {
    formulario: "Facilities",
    codigo: "habitos_alimentares",
    texto: "Hábitos alimentares",
    tipo: "resposta_multipla",
    ordem: 75,
    obrigatoria: false,
    ativa: true,
    opcoes: ["Produção para consumo próprio", "Produção para venda", "Processados para consumo próprio", "Processados para venda", "Alimentos tradicionais para consumo próprio", "Tradicionais para venda", "Consumo habitual de ultraprocessados"],
    allowOther: true,
    categoria: "Comunidade e Cotidiano"
  },
  {
    formulario: "Facilities",
    codigo: "representacao_comunidade",
    texto: "Representação na comunidade",
    tipo: "resposta_multipla",
    ordem: 76,
    obrigatoria: false,
    ativa: true,
    opcoes: ["Associação de moradores", "Grupo de jovens", "Grupo de mães", "Associação Quilombola", "Associação de produtores", "Associação de mulheres artesãs", "Movimento negro", "Grupos culturais", "Conselhos Municipais"],
    allowOther: true,
    categoria: "Comunidade e Cotidiano"
  },
  {
    formulario: "Facilities",
    codigo: "indicacao_profissionais",
    texto: "Profissionais e lojas indicadas pela família:",
    tipo: "texto",
    ordem: 77,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Comunidade e Cotidiano"
  },
  {
    formulario: "Facilities",
    codigo: "recebe_boleto_agua_energia",
    texto: "Estão recebendo boleto de cobrança (talão) de água e energia?",
    tipo: "resposta_unica",
    ordem: 78,
    obrigatoria: false,
    ativa: true,
    opcoes: ["Sim", "Não", "Não deseja ou não sabe informar"],
    categoria: "Comunidade e Cotidiano"
  },
  {
    formulario: "Facilities",
    codigo: "data_primeira_visita_fac",
    texto: "Data da 1º visita",
    tipo: "data",
    ordem: 79,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Gestão da Visita"
  },
  {
    formulario: "Facilities",
    codigo: "observacoes_fac",
    texto: "Observações",
    tipo: "texto",
    ordem: 80,
    obrigatoria: false,
    ativa: true,
    opcoes: [],
    categoria: "Gestão da Visita"
  },

  // PREGUNTAS HISTÓRICAS DESCONTINUADAS
  { formulario: "Facilities", codigo: "tipoLevantamento", texto: "Tipo de Levantamento (Histórico)", tipo: "texto", ordem: 100, obrigatoria: false, ativa: false, opcoes: [], categoria: "Histórico" },
  { formulario: "Facilities", codigo: "adultos_empregados_old", texto: "Adultos Empregados (Histórico)", tipo: "texto", ordem: 101, obrigatoria: false, ativa: false, opcoes: [], categoria: "Histórico" },
  { formulario: "Facilities", codigo: "renda_mensal_total_numeric_old", texto: "Renda Mensal Familiar Total (Numérica Histórica)", tipo: "number", ordem: 102, obrigatoria: false, ativa: false, opcoes: [], categoria: "Histórico" },
  { formulario: "Facilities", codigo: "mulher_chefe_familia_old", texto: "Mulher chefe de família (Histórico)", tipo: "texto", ordem: 103, obrigatoria: false, ativa: false, opcoes: [], categoria: "Histórico" },
  { formulario: "Facilities", codigo: "idoso_chefe_familia_old", texto: "Idoso chefe de família (Histórico)", tipo: "texto", ordem: 104, obrigatoria: false, ativa: false, opcoes: [], categoria: "Histórico" },
  { formulario: "Facilities", codigo: "num_criancas_old", texto: "Quantidade de crianças (Histórico)", tipo: "number", ordem: 105, obrigatoria: false, ativa: false, opcoes: [], categoria: "Histórico" },
  { formulario: "Facilities", codigo: "relacao_aluguel_renda", texto: "O aluguel em relação a renda familiar mensal:", tipo: "texto", ordem: 106, obrigatoria: false, ativa: false, opcoes: [], categoria: "Histórico" }
];

const estruturalQuestions = [
  { formulario: "Edificacoes", codigo: "EST001", texto: "Possui reservatório de água na residência?", tipo: "resposta_unica", ordem: 1, obrigatoria: false, ativa: true, opcoes: ["Caixa d'água", "Agua encanada", "Não sabe informar"], categoria: "Saneamento e Infraestrutura" },
  { formulario: "Edificacoes", codigo: "EST002", texto: "A unidade tem banheiro?", tipo: "resposta_multipla", ordem: 2, obrigatoria: false, ativa: true, opcoes: ["Sim, dentro da casa", "Sim, fora da casa", "Não", "Duchas no quintal"], categoria: "Saneamento e Infraestrutura" },
  { formulario: "Edificacoes", codigo: "EST003", texto: "A unidade tem cozinha?", tipo: "resposta_multipla", ordem: 3, obrigatoria: false, ativa: true, opcoes: ["Sim, dentro de casa", "Sim, fora de casa", "Sim, dentro e fora de casa", "Possui apenas fogão à gás/elétrico", "Possui apenas fogão a lenha", "Possui ambos"], categoria: "Saneamento e Infraestrutura" },
  { formulario: "Edificacoes", codigo: "EST004", texto: "Data da visita:", tipo: "data", ordem: 4, obrigatoria: false, ativa: true, opcoes: [], categoria: "Gestão do Formulário" },
  { formulario: "Edificacoes", codigo: "EST005", texto: "Nome do responsável pelo formulário:", tipo: "texto", ordem: 5, obrigatoria: false, ativa: true, opcoes: [], categoria: "Gestão do Formulário" },
  { formulario: "Edificacoes", codigo: "EST006", texto: "Nome do responsável pelo relatório fotográfico:", tipo: "texto", ordem: 6, obrigatoria: false, ativa: true, opcoes: [], categoria: "Gestão do Formulário" },
  { formulario: "Edificacoes", codigo: "EST007", texto: "Nome do responsável pelo levantamento arquitetônico:", tipo: "texto", ordem: 7, obrigatoria: false, ativa: true, opcoes: [], categoria: "Gestão do Formulário" },
  { formulario: "Edificacoes", codigo: "EST008", texto: "Nome do agente comunitário:", tipo: "texto", ordem: 8, obrigatoria: false, ativa: true, opcoes: [], categoria: "Gestão do Formulário" },
  { formulario: "Edificacoes", codigo: "EST009", texto: "Outros profissionais envolvidos (nomes e funções desempenhadas):", tipo: "texto", ordem: 9, obrigatoria: false, ativa: true, opcoes: [], categoria: "Gestão do Formulário" },
  { formulario: "Edificacoes", codigo: "EST010", texto: "Demanda apresentada pela família:", tipo: "texto", ordem: 10, obrigatoria: false, ativa: true, opcoes: [], categoria: "Diagnóstico e Demandas" },
  { formulario: "Edificacoes", codigo: "EST011", texto: "ID", tipo: "texto", ordem: 11, obrigatoria: false, ativa: true, opcoes: [], categoria: "Identificação" },
  { formulario: "Edificacoes", codigo: "EST012", texto: "Nome do Morador:", tipo: "texto", ordem: 12, obrigatoria: false, ativa: true, opcoes: [], categoria: "Identificação" },
  { formulario: "Edificacoes", codigo: "EST013", texto: "Há problemas de insalubridade com:", tipo: "resposta_multipla", ordem: 13, obrigatoria: false, ativa: true, opcoes: ["Áreas molhadas", "Aberturas", "Coberturas", "Revestimento", "Não se aplica", "Infiltração", "Umidade ascendente", "Problemas sanitários", "Conforto térmico"], allowOther: true, categoria: "Condições Habitacionais" },
  { formulario: "Edificacoes", codigo: "EST014", texto: "Existe a necessidade de realização de reparos estruturais?", tipo: "resposta_unica", ordem: 14, obrigatoria: false, ativa: true, opcoes: ["Sim", "Não", "Verificar com o Engenheiro"], categoria: "Condições Habitacionais" },
  { formulario: "Edificacoes", codigo: "EST016", texto: "Existe a possibilidade de resolver os problemas dentro do próprio terreno (a partir da\nestrutura existente)?", tipo: "resposta_unica", ordem: 15, obrigatoria: false, ativa: true, opcoes: ["Sim", "Não"], allowOther: true, categoria: "Condições Habitacionais" },
  { formulario: "Edificacoes", codigo: "EST017", texto: "De acordo com a defesa civil? A edificação encontra-se em área de risco?", tipo: "resposta_multipla", ordem: 16, obrigatoria: false, ativa: true, opcoes: ["Não", "R1", "R2", "R3", "R4"], allowOther: true, categoria: "Condições Habitacionais" },
  { formulario: "Edificacoes", codigo: "EST018", texto: "Número de quartos:", tipo: "number", ordem: 17, obrigatoria: false, ativa: true, opcoes: [], categoria: "Condições Habitacionais" },
  { formulario: "Edificacoes", codigo: "EST019", texto: "Superpopulação:", tipo: "texto", ordem: 18, obrigatoria: false, ativa: true, opcoes: [], categoria: "Condições Habitacionais" },
  { formulario: "Edificacoes", codigo: "EST020", texto: "Coabitação:", tipo: "resposta_unica", ordem: 19, obrigatoria: false, ativa: true, opcoes: ["Sim", "Não"], allowOther: true, categoria: "Condições Habitacionais" },
  { formulario: "Edificacoes", codigo: "EST021", texto: "Inserção no lote:", tipo: "resposta_unica", ordem: 20, obrigatoria: false, ativa: true, opcoes: ["1", "2", "3"], categoria: "Avaliação Estrutural e Física" },
  { formulario: "Edificacoes", codigo: "EST022", texto: "Fundações:", tipo: "resposta_unica", ordem: 21, obrigatoria: false, ativa: true, opcoes: ["1", "2", "3"], categoria: "Avaliação Estrutural e Física" },
  { formulario: "Edificacoes", codigo: "EST023", texto: "Estrutura:", tipo: "resposta_unica", ordem: 22, obrigatoria: false, ativa: true, opcoes: ["1", "2", "3"], categoria: "Avaliação Estrutural e Física" },
  { formulario: "Edificacoes", codigo: "EST024", texto: "Paredes:", tipo: "resposta_unica", ordem: 23, obrigatoria: false, ativa: true, opcoes: ["1", "2", "3"], categoria: "Avaliação Estrutural e Física" },
  { formulario: "Edificacoes", codigo: "EST025", texto: "Cobertura:", tipo: "resposta_unica", ordem: 24, obrigatoria: false, ativa: true, opcoes: ["1", "2", "3"], categoria: "Avaliação Estrutural e Física" },
  { formulario: "Edificacoes", codigo: "EST026", texto: "Esquadrias:", tipo: "resposta_unica", ordem: 25, obrigatoria: false, ativa: true, opcoes: ["1", "2", "3"], categoria: "Avaliação Estrutural e Física" },
  { formulario: "Edificacoes", codigo: "EST027", texto: "Hidrossanitário:", tipo: "resposta_unica", ordem: 26, obrigatoria: false, ativa: true, opcoes: ["1", "2", "3"], categoria: "Avaliação Estrutural e Física" },
  { formulario: "Edificacoes", codigo: "EST028", texto: "Elétrico:", tipo: "resposta_unica", ordem: 27, obrigatoria: false, ativa: true, opcoes: ["1", "2", "3"], categoria: "Avaliação Estrutural e Física" },
  { formulario: "Edificacoes", codigo: "EST029", texto: "Banheiro(s):", tipo: "resposta_unica", ordem: 28, obrigatoria: false, ativa: true, opcoes: ["1", "2", "3"], categoria: "Avaliação Estrutural e Física" },
  { formulario: "Edificacoes", codigo: "EST030", texto: "Cozinha/área de serviço:", tipo: "resposta_unica", ordem: 29, obrigatoria: false, ativa: true, opcoes: ["1", "2", "3"], categoria: "Avaliação Estrutural e Física" },
  { formulario: "Edificacoes", codigo: "EST031", texto: "Conforto:", tipo: "resposta_unica", ordem: 30, obrigatoria: false, ativa: true, opcoes: ["1", "2", "3"], categoria: "Avaliação Estrutural e Física" },
  { formulario: "Edificacoes", codigo: "EST032", texto: "Avaliação da residência:", tipo: "resposta_unica", ordem: 31, obrigatoria: false, ativa: true, opcoes: ["Reforma", "Reconstrução", "Expansão", "Nova unidade", "Precisa de mais avaliação", "Não necessita de alterações"], categoria: "Diagnóstico e Parecer" },
  { formulario: "Edificacoes", codigo: "EST033", texto: "A circulação interna na unidade é segura e adequada para todos os membros da família?", tipo: "resposta_unica", ordem: 32, obrigatoria: false, ativa: true, opcoes: ["Sim", "Não"], categoria: "Diagnóstico e Parecer" },
  { formulario: "Edificacoes", codigo: "EST034", texto: "Como você avaliaria a infraestrutura urbana no entorno da residência?", tipo: "resposta_unica", ordem: 33, obrigatoria: false, ativa: true, opcoes: ["1", "2", "3"], categoria: "Entorno Urbano" },
  { formulario: "Edificacoes", codigo: "EST035", texto: "Como você avaliaria a acessibilidade, transporte, lazer, saneamento básico e serviços?", tipo: "texto", ordem: 34, obrigatoria: false, ativa: true, opcoes: [], categoria: "Entorno Urbano" },
  { formulario: "Edificacoes", codigo: "EST036", texto: "Na sua opinião, qual a situação geral da casa?", tipo: "resposta_unica", ordem: 35, obrigatoria: false, ativa: true, opcoes: ["1", "2", "3"], categoria: "Diagnóstico e Parecer" },
  { formulario: "Edificacoes", codigo: "EST037", texto: "Diagnóstico preliminar:", tipo: "texto", ordem: 36, obrigatoria: false, ativa: true, opcoes: [], categoria: "Diagnóstico e Parecer" },
  { formulario: "Edificacoes", codigo: "EST038", texto: "Aponte pelo menos uma situação positiva da edificação que você observou.", tipo: "texto", ordem: 37, obrigatoria: false, ativa: true, opcoes: [], categoria: "Diagnóstico e Parecer" },
  { formulario: "Edificacoes", codigo: "EST039", texto: "Observações gerais:", tipo: "texto", ordem: 38, obrigatoria: false, ativa: true, opcoes: [], categoria: "Diagnóstico e Parecer" }
];

module.exports = { facilitiesQuestions, estruturalQuestions, legacySourceQuestions: [] };